title: "GreenTea"
theme: jekyll-theme-slate

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S1-CS2103T-T09-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
